/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as LibAbiEncoder from '../generated-artifacts/LibAbiEncoder.json.js';
import * as LibAssetProxyErrors from '../generated-artifacts/LibAssetProxyErrors.json.js';
import * as LibConstants from '../generated-artifacts/LibConstants.json.js';
import * as LibEIP712 from '../generated-artifacts/LibEIP712.json.js';
import * as LibFillResults from '../generated-artifacts/LibFillResults.json.js';
import * as LibMath from '../generated-artifacts/LibMath.json.js';
import * as LibOrder from '../generated-artifacts/LibOrder.json.js';
import * as TestLibs from '../generated-artifacts/TestLibs.json.js';
export const artifacts = {
    LibAbiEncoder: LibAbiEncoder as ContractArtifact,
    LibAssetProxyErrors: LibAssetProxyErrors as ContractArtifact,
    LibConstants: LibConstants as ContractArtifact,
    LibEIP712: LibEIP712 as ContractArtifact,
    LibFillResults: LibFillResults as ContractArtifact,
    LibMath: LibMath as ContractArtifact,
    LibOrder: LibOrder as ContractArtifact,
    TestLibs: TestLibs as ContractArtifact,
};
